import Foundation

enum TransportKind: String, Codable, CaseIterable, Identifiable {
  case tcp
  var id: String { rawValue }
}

enum PayloadKind: String, Codable, CaseIterable, Identifiable {
  case text
  case hex
  var id: String { rawValue }
}

enum TextEncodingKind: String, Codable, CaseIterable, Identifiable {
  case utf8
  case gb18030
  var id: String { rawValue }
}

enum LineEnding: String, Codable, CaseIterable, Identifiable {
  case crlf
  case lf
  case cr
  case none
  var id: String { rawValue }

  var bytes: Data {
    switch self {
    case .crlf: return Data([0x0D, 0x0A])
    case .lf:   return Data([0x0A])
    case .cr:   return Data([0x0D])
    case .none: return Data()
    }
  }

  var displayName: String {
    switch self {
    case .crlf: return "\\r\\n (CRLF)"
    case .lf:   return "\\n (LF)"
    case .cr:   return "\\r (CR)"
    case .none: return "None"
    }
  }
}

enum ControlType: String, Codable, CaseIterable, Identifiable {
  case button
  case slider
  case toggle
  case label
  case icon
  case border
  case matrix
  case liveMatrix
  case volumeLevel
  case matrixInput
  case matrixOutput
  case liveMatrixInput
  case liveMatrixOutput
  var id: String { rawValue }

  /// True for chip types generated by exploding a matrix parent.
  var isMatrixChip: Bool {
    self == .matrixInput || self == .matrixOutput
      || self == .liveMatrixInput || self == .liveMatrixOutput
  }
}

enum BehaviorKind: String, Codable, CaseIterable, Identifiable {
  case momentary
  case toggle
  case radio
  var id: String { rawValue }
}

struct UnifiedControlModel: Codable, Equatable {
  var meta: Meta = .init()
  var devices: [DeviceItem] = []
  var commands: [CommandItem] = []
  var controls: [ControlItem] = []
  var layouts: [LayoutItem] = [.defaultLayout]
  var styles: StyleItem = .init()
  var rules: RuleItem = .init()
  var triggerRules: [CommandTriggerRule] = []
}

// MARK: - Command Trigger Rules

enum TriggerSource: String, Codable, CaseIterable, Identifiable {
  case incoming  // 监听设备返回的报文
  case outgoing  // 监听 App 发出的命令
  var id: String { rawValue }
  var displayName: String {
    switch self {
    case .incoming: return "收到报文"
    case .outgoing: return "发出命令"
    }
  }
}

enum TriggerMatchMode: String, Codable, CaseIterable, Identifiable {
  case contains
  case prefix
  case suffix
  case regex
  var id: String { rawValue }
  var displayName: String {
    switch self {
    case .contains: return "包含"
    case .prefix:   return "前缀"
    case .suffix:   return "后缀"
    case .regex:    return "正则"
    }
  }
}

/// A single action within a trigger rule — send one command to one device.
struct TriggerAction: Codable, Equatable, Identifiable {
  var id: UUID = UUID()
  var deviceID: UUID?
  var commandID: UUID?
  /// Optional delay before sending this action (milliseconds).
  var delayMs: Int = 0
}

struct CommandTriggerRule: Codable, Equatable, Identifiable {
  var id: UUID = UUID()
  var name: String = ""
  var enabled: Bool = true
  // 触发条件
  var source: TriggerSource = .incoming
  var watchDeviceID: UUID?        // nil = 所有设备
  var pattern: String = ""
  var matchMode: TriggerMatchMode = .contains
  // 触发动作（支持多条，按顺序执行）
  var actions: [TriggerAction] = []
  // 防抖：同一规则两次触发的最小间隔（毫秒）
  var cooldownMs: Int = 500
}

struct Meta: Codable, Equatable {
  var schemaVersion: Int = 1
  var updatedAt: Date = Date()
  var snapshotID: String = UUID().uuidString
}

struct DeviceItem: Codable, Equatable, Identifiable {
  var id: UUID = UUID()
  var name: String
  var host: String
  var port: Int
  var transport: TransportKind = .tcp
  var encoding: TextEncodingKind = .utf8
  /// When true, TCP connections to this device are kept alive and reused
  /// across commands. Set to false for devices that close the connection
  /// after each command.
  var keepAlive: Bool = true
}

struct CommandItem: Codable, Equatable, Identifiable {
  var id: UUID = UUID()
  var name: String
  var payloadKind: PayloadKind
  var payload: String
  var lineEnding: LineEnding = .crlf
  var timeoutMs: Int = 1500
}

struct ControlBinding: Codable, Equatable {
  var deviceID: UUID
  var commandID: UUID
}

/// Grid placement stored in **cell units** (Double for sub-cell precision).
/// JSON backward-compatible: existing integer values decode as Double without changes.
struct Placement: Codable, Equatable {
  var x: Double
  var y: Double
  var w: Double
  var h: Double
}

struct ControlItem: Codable, Equatable, Identifiable {
  var id: UUID = UUID()
  var type: ControlType
  var title: String
  var behavior: BehaviorKind = .momentary
  var groupKey: String?
  var binding: ControlBinding?
  var placement: Placement
  var customFields: [String: String] = [:]
}

extension ControlItem {
  /// Set after "explode to chips": parent matrix stays in the model (for `parentControlID` and inspector) but is not shown on canvas or runtime.
  static let matrixExplodedToChipsKey = "matrixExplodedToChips"
  /// Grid cell origin saved at first explode (parent placement before it is zeroed) — used to place additional chips when I/O counts increase.
  static let matrixExplodeOriginXKey = "matrixExplodeOriginX"
  static let matrixExplodeOriginYKey = "matrixExplodeOriginY"
  var isExplodedMatrixParentHiddenFromCanvas: Bool {
    (type == .matrix || type == .liveMatrix) && customFields[Self.matrixExplodedToChipsKey] == "1"
  }
}

struct LayoutItem: Codable, Equatable, Identifiable {
  var id: UUID = UUID()
  var breakpoint: Int
  var columns: Int
  var spacing: Double

  static let defaultLayout = LayoutItem(breakpoint: 0, columns: 8, spacing: 10)
}

enum UIStyleTheme: String, Codable, CaseIterable, Identifiable {
  case dark
  case light
  case glass
  case midnight
  case ocean
  case warmGray
  case lightBlue
  case lightMint
  case lightPink
  case lightLavender
  case lightSand
  case lightPeach
  case lightLemon
  case lightSage
  case lightCoral
  case lightIce
  case pureWhite
  var id: String { rawValue }

  var displayName: String {
    switch self {
    case .dark: return "Dark"
    case .light: return "Light"
    case .glass: return "Glass"
    case .midnight: return "Midnight"
    case .ocean: return "Ocean"
    case .warmGray: return "Warm Gray"
    case .lightBlue: return "Sky Blue"
    case .lightMint: return "Mint Fresh"
    case .lightPink: return "Rose"
    case .lightLavender: return "Lavender"
    case .lightSand: return "Sand"
    case .lightPeach: return "Peach"
    case .lightLemon: return "Lemon"
    case .lightSage: return "Sage"
    case .lightCoral: return "Coral"
    case .lightIce: return "Ice"
    case .pureWhite: return "Pure White"
    }
  }
}

struct StyleItem: Codable, Equatable {
  var logoPath: String?
  var backgroundPath: String?
  var fontName: String = "System"
  var glowOpacity: Double = 0.35
  var shadowBlur: Double = 10
  var shadowY: Double = 4
  var logoWidth: Double = 120
  var logoHeight: Double = 40
  var logoX: Double = 20
  var logoY: Double = 10
  var uiTheme: UIStyleTheme = .dark
}

struct RuleItem: Codable, Equatable {
  var busyPolicy: String = "disable_same_control"
  var errorPolicy: String = "set_error_state"
}
